# Generated by Django 5.2.3 on 2025-07-12 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#007bff', help_text='Cor em hexadecimal (ex: #007bff)', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(help_text='Descrição detalhada do problema')),
                ('solucao', models.TextField(help_text='Procedimento passo-a-passo para resolver')),
                ('tags', models.CharField(help_text='Tags separadas por vírgula (ex: rede, servidor, windows)', max_length=500)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para arquivar o procedimento')),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='procedimentos.categoria')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='procedimentos.procedimento')),
            ],
            options={
                'verbose_name': 'Histórico de Procedimento',
                'verbose_name_plural': 'Histórico de Procedimentos',
                'ordering': ['-data'],
            },
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['categoria', 'ativo'], name='procediment_categor_8c91a5_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['prioridade'], name='procediment_priorid_303df9_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['tags'], name='procediment_tags_69cffa_idx'),
        ),
    ]
