# Generated by Django 5.2.3 on 2025-07-14 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, help_text='Nome do ícone FontAwesome (ex: fas fa-network-wired)', max_length=50),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='eficacia',
            field=models.PositiveIntegerField(default=0, help_text='Número de vezes que resolveu o problema'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem ilustrativa do problema ou solução', null=True, upload_to='procedimentos/imagens/'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='link_externo',
            field=models.URLField(blank=True, help_text='Link para documentação externa'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('revisao', 'Em Revisão'), ('desatualizado', 'Desatualizado'), ('arquivado', 'Arquivado')], default='ativo', max_length=15),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL do vídeo explicativo (YouTube, Vimeo, etc.)'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente específico (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimentos', to='procedimentos.cliente'),
        ),
    ]
