# Generated by Django 5.1.1 on 2025-07-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='processado',
            field=models.BooleanField(default=False),
        ),
    ]
