# Generated by Django 5.1.1 on 2025-07-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='local',
            field=models.CharField(blank=True, default='unknown', max_length=255),
        ),
    ]
